<a href="https://colab.research.google.com/github/amruthavarshinidara/ML_LAB_2026-27/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



**Pandas Python Library**

**Introduction to Pandas**

Pandas is an open-source software library written for the Python programming language, primarily used for data manipulation and analysis. It provides powerful and flexible data structures designed to make working with tabular and time-series data both easy and intuitive.

**Key features and functionalities of Pandas include: Data Structures:**

Pandas introduces two primary data structures:

**Series:** A one-dimensional labeled array capable of holding any data type. It can be thought of as a single column in a spreadsheet.

**DataFrame: **A two-dimensional labeled data structure with columns of potentially different data types. It is similar to a spreadsheet or SQL table, providing a powerful way to represent and manipulate tabular data.

**What is pandas used for?**

pandas is used throughout the data analysis workflow. With pandas, you can:

    1.Import datasets from databases, spreadsheets, comma-separated values (CSV) files, and more.

    2.Clean datasets, for example, by dealing with missing values.

    3.Tidy datasets by reshaping their structure into a suitable format for analysis.

    4.Aggregate data by calculating summary statistics such as the mean of columns, correlation between them, and more.

    5.Visualize datasets and uncover insights.

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("/content/sample_data/california_housing_train.csv")

In [3]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [4]:
df.tail()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [5]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [17]:
import pandas as pd

In [18]:
df=pd.read_excel("/content/student.marks.xlsx")

In [19]:
df.head()

      Roll  No        Student Name     DM  ATCD  DBMS      IAI   JAVA
0   24AG1A66E5  D.Amrutha Varshini     92    85    87       89     95
1   24AG1A66G7             L.Sneha     70    80    70       85     85
2  24AG1A66EI8            V.Shrija     90    85    89       87     92
3   24AG1A66H5           M.Anvitha     80    88    77       65     72
4   24AG1A66E9           D.Sahasra     81    87    79       75     69

In [20]:
df.tail()

     Roll  No    Student Name     DM  ATCD  DBMS      IAI   JAVA
5  24AG1A66I7          Tapasi     95    99    92       93     94
6  24AG1A66J2  V.Sai Teja Sri     60    78    66       68     71
7  24AG1A66E1       E.Sharoon     75    81    82       79     77
8  24AG1A66J1      J.Susmitha     65    76    68       72     71
9  24AG1A66I4       Pravalika     75    81    82       79     72

In [21]:
df.describe()

              DM       ATCD       DBMS       IAI       JAVA
count  10.000000  10.000000  10.000000  10.00000  10.000000
mean   78.300000  84.000000  79.200000  79.20000  79.800000
std    11.624208   6.548961   8.978988   9.29516  10.591401
min    60.000000  76.000000  66.000000  65.00000  69.000000
25%    71.250000  80.250000  71.750000  72.75000  71.250000
50%    77.500000  83.000000  80.500000  79.00000  74.500000
75%    87.750000  86.500000  85.750000  86.50000  90.250000
max    95.000000  99.000000  92.000000  93.00000  95.000000

In [22]:
df.columns

Index(['       Roll  No', '      Student Name', '        DM', '     ATCD',
       '     DBMS', '         IAI', '      JAVA'],
      dtype='object')

In [23]:
import pandas as pd

In [29]:
df=pd.read_csv("/content/Sheet1.csv")

In [27]:
df.head()

      Roll  No        Student Name     DM  ATCD  DBMS      IAI   JAVA
0   24AG1A66E5  D.Amrutha Varshini     92    85    87       89     95
1   24AG1A66G7             L.Sneha     70    80    70       85     85
2  24AG1A66EI8            V.Shrija     90    85    89       87     92
3   24AG1A66H5           M.Anvitha     80    88    77       65     72
4   24AG1A66E9           D.Sahasra     81    87    79       75     69

In [30]:
df.tail()

     Roll  No    Student Name     DM  ATCD  DBMS      IAI   JAVA
5  24AG1A66I7          Tapasi     95    99    92       93     94
6  24AG1A66J2  V.Sai Teja Sri     60    78    66       68     71
7  24AG1A66E1       E.Sharoon     75    81    82       79     77
8  24AG1A66J1      J.Susmitha     65    76    68       72     71
9  24AG1A66I4       Pravalika     75    81    82       79     72

In [31]:
df.describe()

              DM       ATCD       DBMS       IAI       JAVA
count  10.000000  10.000000  10.000000  10.00000  10.000000
mean   78.300000  84.000000  79.200000  79.20000  79.800000
std    11.624208   6.548961   8.978988   9.29516  10.591401
min    60.000000  76.000000  66.000000  65.00000  69.000000
25%    71.250000  80.250000  71.750000  72.75000  71.250000
50%    77.500000  83.000000  80.500000  79.00000  74.500000
75%    87.750000  86.500000  85.750000  86.50000  90.250000
max    95.000000  99.000000  92.000000  93.00000  95.000000

In [33]:
import pandas as pd

In [34]:


df=pd.read_json("/content/Sheet1.json")

In [35]:
df.head()

      Roll  No        Student Name     DM  ATCD  DBMS      IAI   JAVA
0   24AG1A66E5  D.Amrutha Varshini     92    85    87       89     95
1   24AG1A66G7             L.Sneha     70    80    70       85     85
2  24AG1A66EI8            V.Shrija     90    85    89       87     92
3   24AG1A66H5           M.Anvitha     80    88    77       65     72
4   24AG1A66E9           D.Sahasra     81    87    79       75     69

In [36]:
df.describe()

              DM       ATCD       DBMS       IAI       JAVA
count  10.000000  10.000000  10.000000  10.00000  10.000000
mean   78.300000  84.000000  79.200000  79.20000  79.800000
std    11.624208   6.548961   8.978988   9.29516  10.591401
min    60.000000  76.000000  66.000000  65.00000  69.000000
25%    71.250000  80.250000  71.750000  72.75000  71.250000
50%    77.500000  83.000000  80.500000  79.00000  74.500000
75%    87.750000  86.500000  85.750000  86.50000  90.250000
max    95.000000  99.000000  92.000000  93.00000  95.000000

In [37]:
df.tail()

     Roll  No    Student Name     DM  ATCD  DBMS      IAI   JAVA
5  24AG1A66I7          Tapasi     95    99    92       93     94
6  24AG1A66J2  V.Sai Teja Sri     60    78    66       68     71
7  24AG1A66E1       E.Sharoon     75    81    82       79     77
8  24AG1A66J1      J.Susmitha     65    76    68       72     71
9  24AG1A66I4       Pravalika     75    81    82       79     72